"""align defaults/nullability

Revision ID: 2d2f9f2fa092
Revises: 4fd8aa168235
Create Date: 2026-01-24 11:09:57.377489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d2f9f2fa092'
down_revision: Union[str, Sequence[str], None] = '4fd8aa168235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("UPDATE accounts SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE clients SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE clients SET status = 'ACTIVE'::clientstatus WHERE status IS NULL")
    op.execute("UPDATE idempotency_keys SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE ledger_entries SET created_at = now() WHERE created_at IS NULL")

    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('clients', 'api_key_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'DELETED', name='clientstatus'),
               nullable=False)
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ledger_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('clients', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'DELETED', name='clientstatus'),
               nullable=True)
    op.alter_column('clients', 'api_key_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
