"""add account and ledger check constraints

Revision ID: 504568161e66
Revises: 2d2f9f2fa092
Create Date: 2026-03-15 20:51:35.743473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504568161e66'
down_revision: Union[str, Sequence[str], None] = '2d2f9f2fa092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_accounts_credit_limit_non_negative",
        "accounts",
        "credit_limit IS NULL OR credit_limit >= 0",
    )

    op.create_check_constraint(
        "ck_accounts_balance_type_credit_limit",
        "accounts",
        "(balance_type = 'DEBIT_ONLY' AND credit_limit IS NULL) OR "
        "(balance_type = 'CREDIT_ALLOWED' AND credit_limit IS NOT NULL)",
    )

    op.create_check_constraint(
        "ck_ledger_entries_entry_type_amount_sign",
        "ledger_entries",
        "(entry_type = 'DEBIT' AND amount < 0) OR "
        "(entry_type = 'CREDIT' AND amount > 0)",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_ledger_entries_entry_type_amount_sign", "ledger_entries", type_="check")
    op.drop_constraint("ck_accounts_balance_type_credit_limit", "accounts", type_="check")
    op.drop_constraint("ck_accounts_credit_limit_non_negative", "accounts", type_="check")

    # ### end Alembic commands ###
